[JET-1160] refactor: stop modifing tenant schema
Byzanteam/jet-plugin-sdk pull request #43
Opened 2024-03-20 09:40 UTC by vanppo

2024-03-20 10:14 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +      reply when is_tuple(reply) and tuple_size(reply) in [3, 4] and elem(reply, 0) === :reply ->
这里没有更新 state.tenant 上的 config 的值

2024-03-20 10:14 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +  def update_config(tenant_module, tenant_id, config) do
callback 现在改成了 handle_update，这里也改成 update 吧，另外为下一步做 capabilities 的 update 准备一下

```suggestion
  @spec update(
          tenant_module :: module(),
          tenant_id :: tenant_id(),
          params :: %{config: tenant_config()}
        ) :: term()
  def update(tenant_module, tenant_id, params) do
```

2024-03-20 10:16 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +      reply when is_tuple(reply) and tuple_size(reply) in [3, 4] and elem(reply, 0) === :reply ->
这里有个疑问，如果 update 失败了，sdk 要感知到吗，比如如果 update 失败了，就不更新 state.tenant 上的 config ？

2024-03-20 13:40 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +      reply when is_tuple(reply) and tuple_size(reply) in [3, 4] and elem(reply, 0) === :reply ->
不是说不更新 tenant 上面的值吗

2024-03-20 15:19 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +      reply when is_tuple(reply) and tuple_size(reply) in [3, 4] and elem(reply, 0) === :reply ->
是不允许用户更新，它自己的更新还是要有的

2024-03-21 01:59 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +      reply when is_tuple(reply) and tuple_size(reply) in [3, 4] and elem(reply, 0) === :reply ->
如果要更新 config 那就需要知道有没有成功了

2024-03-21 02:07 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +      reply when is_tuple(reply) and tuple_size(reply) in [3, 4] and elem(reply, 0) === :reply ->
但是这么一来的话 reply 都还好 noreply 就没办法判断了哦

2024-03-22 05:54 UTC, fahchen requested changes

2024-03-22 05:54 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
这个要不要改成 handle_install 啊？

2024-03-22 05:54 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +    apply(m, f, a)
arg 要把 state 塞进去一下

2024-03-22 05:54 UTC, fahchen commented on test/jet_plugin_sdk/tenant_man/tenants/tenant_test.exs
补一下异步的测试

2024-03-22 06:16 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +    apply(m, f, a)
不用吧 如果真的有需要的话 开发者可以自己放到 a 里面

2024-03-22 06:19 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
那 init 还需要保留么 如果保留的话又有什么用呢

2024-03-22 06:25 UTC, CptBreeza commented on lib/jet_plugin_sdk/tenant_man/registry.ex
> +  @type name() :: {:via, Registry, {__MODULE__, key()}}
现在这种写法的话相当于把 name 长啥样这个细节暴露给外面的用户了，这个类型我觉得不用这么细致，直接用 `GenServer.name()` 就可以了

2024-03-22 06:25 UTC, CptBreeza commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
感觉就没有必要再留一个 init callback 给用户了

2024-03-22 06:25 UTC, CptBreeza commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +    |> case do
只有一步的 pipeline 就直接写进去吧：
```elixir
case apply(m, f, a) do
```

2024-03-22 06:58 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +              | {:async, mfa()}
支持 mfa 的同时也支持一下函数捕获呢，这样用起来比较方便，不用暴露 public 函数

2024-03-22 06:58 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +  @callback handle_update(config :: tenant_config(), from :: GenServer.from(), state()) ::
from 我觉得没有必要了
```suggestion
  @callback handle_update(config :: tenant_config(), state()) ::
```

2024-03-22 06:58 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
不用保留了
但还要处理一些情况，通过 warm up 启动起来的，需要根据 tenant 的不同 state 去完成不同的事情，比如处于 updating 状态的，需要完成 update 的任务然后回报状态给 jet 等

2024-03-22 07:30 UTC, CptBreeza commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
这些都是当前咱们评论的这个模块它自己来处理吧，而不需要用户实现 init 回调去处理

2024-03-22 07:59 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
那像是校验 config 这样的操作放到哪里去做呢

2024-03-22 08:02 UTC, CptBreeza commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
>    @callback init(tenant :: tenant_schema()) ::
不是要新做一个 handle_install 吗，install 这个动作应该需要一个专门的 GenServer.call 了吧，而不是像之前那样放到 init 里面去做
cc @fahchen

2024-03-22 08:03 UTC, fahchen reviewed
通过 warmup 的启动逻辑要处理下

https://github.com/Byzanteam/jet-plugin-sdk/pull/43#discussion_r1535129861

2024-03-22 08:03 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:reply, {:error, reason}, state}
error 是不是也可以支持 extra 参数或者 tenant_state 的更新？

2024-03-25 09:07 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:reply, {:error, reason}, state}
感觉没有必要呢 install 出错的话应该让 Jet 知晓 然后这个 tenant 处于异常的状态吧

2024-03-25 13:12 UTC, fahchen requested changes

2024-03-25 13:12 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:reply, {:error, reason}, state}
但是谁来停掉这个 GenServer 呢？这里提供 extra 可以用来停掉 GenServer 并做 cleanup 的操作
如果这个要增加，其他几个 callback 应该也要加

2024-03-26 02:09 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:reply, {:error, reason}, state}
`{:stop, reason, reply, new_state}` 这样停止吧

2024-03-26 08:14 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:reply, {:error, reason}, state}
```suggestion
        {:stop, reason, {:error, reason}, state}
```

2024-03-26 08:15 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:stop, reason, {:error, reason}, state}
```suggestion
        {:reply, {:error, reason}, state}
```

2024-03-26 08:16 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/tenants/tenant.ex
> +        {:reply, {:error, reason}, state}
```suggestion
        {:stop, reason, {:error, reason}, state}
```

2024-03-26 09:12 UTC, CptBreeza approved these changes

2024-03-26 09:40 UTC, fahchen approved these changes

2024-03-26 10:15 UTC, CptBreeza approved these changes

2024-03-26 15:02 UTC, merged