[JET-1212] refactor: manage tenant state via ETS table
Byzanteam/jet-plugin-sdk pull request #51
Opened 2024-04-16 06:37 UTC by vanppo

- [x] 写操作通过 GenServer 顺序写入
- [x] 读操作直接从 ETS 上并发读取

2024-04-16 07:33 UTC, fahchen requested changes

2024-04-16 07:47 UTC, vanppo commented on test/jet_plugin_sdk/tenant_man/tenants/tenant_test.exs
> +
6

2024-04-16 07:49 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +  end
这里写入的操作才是通过 call 来做的 read concurrency 应该是有用的吧

2024-04-16 07:50 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +  @typep state() :: term()
你这个作者自己去维护是什么意思 自己找个地方去存储吗

2024-04-16 07:51 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +  end
我的，看错了

2024-04-16 07:52 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +    {:ok, :ets.new(__MODULE__, [:named_table, read_concurrency: true])}
这个的 public 是不是要设置下呀，不然其他的 process 无法调用 `fetch/1`

2024-04-16 07:56 UTC, vanppo commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +    {:ok, :ets.new(__MODULE__, [:named_table, read_concurrency: true])}
public 是其他 process 可以读写，默认情况是只读，这里写的操作是通过 call 去做的，所以默认的权限就可以了。

2024-04-16 07:58 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +  @typep state() :: term()
嗯，我想的是 storage 只存储 tenant 相关的信息，它维护从 jet 获取的 config，capabilities 等信息
至于其他业务的信息如果作者想要共享，他应该自己找地方存储

2024-04-16 10:20 UTC, fahchen commented on lib/jet_plugin_sdk/tenant_man/storage.ex
> +  end
试试这个方案 insert 的时候 monitor 一下对应的 tenant，然后它 DOWN 了，我们就自动删除，避免手动管理

2024-04-17 02:37 UTC, fahchen approved these changes

2024-04-17 03:14 UTC, c01dcat approved these changes

2024-04-17 03:22 UTC, merged